DEFAULTS: &DEFAULTS
    adapter: <%= ENV["DATABASE_ADAPTER"] %>
    encoding: <%= ENV["DATABASE_ENCODING"] %>
    host: <%= ENV["DATABASE_HOST"] %>
    port: <%= ENV["DATABASE_PORT"] %>
    username: <%= ENV["DATABASE_USERNAME"] %>
    password: <%= ENV["DATABASE_PASSWORD"] %>  
    
development:
    <<: *DEFAULTS
    database: <%= ENV["DEVELOPMENT_DATABASE"] %> 
    
test:
    <<: *DEFAULTS
    database: <%= ENV["TEST_DATABASE"] %>
    
staging:
    <<: *DEFAULTS
    database: <%= ENV["STAGING_DATABASE"] %>    

production:
    <<: *DEFAULTS
    database: <%= ENV["PRODUCTION_DATABASE"] %> 
